route:
  target:
    entity:
      integration: av_matrix
      domain: select
  fields:
    destination:
      required: false
      advanced: true
      example: "dante-network_STAGEBOX:1"
      selector:
        text:
          multiple: true
    source:
      required: true
      example: "STUDIO-PC (Slides)"
      selector:
        text:

salvo:
  fields:
    routes:
      required: true
      example: '[{"destination": "select.lobby_screen_source", "source": "STUDIO-PC (Slides)"}, {"destination": "select.stage_screen_source", "source": "None"}]'
      selector:
        object:

lock:
  target:
    entity:
      integration: av_matrix
      domain: select
  fields:
    destination:
      required: false
      advanced: true
      example: "dante-network_STAGEBOX:1"
      selector:
        text:
          multiple: true

unlock:
  target:
    entity:
      integration: av_matrix
      domain: select
  fields:
    destination:
      required: false
      advanced: true
      example: "dante-network_STAGEBOX:1"
      selector:
        text:
          multiple: true

undo:
  target:
    entity:
      integration: av_matrix
      domain: select
  fields:
    destination:
      required: false
      advanced: true
      example: "dante-network_STAGEBOX:1"
      selector:
        text:
          multiple: true

refresh_sources:
  target:
    entity:
      integration: av_matrix
      domain: select
  fields:
    destination:
      required: false
      advanced: true
      example: "dante-network_STAGEBOX:1"
      selector:
        text:
          multiple: true
